version: "3"

services:
  vue-neutralino:
    container_name: "vue-neutralino"
    image: "node:18.13.0-alpine"
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: '/var/www/html/vue'
    volumes:
      - ../:/var/www/html
    stdin_open: true
